pipeline {
    agent any
    environment {
        REALASE="20.4"

    }
    stages {
        stage('Build'){
            environment {
                LOG_LEVEL='INFO'

            }
            steps {
                echo "Building realase ${REALASE} with log level ${LOG_LEVEL}"

            }
        }
        stage('Test'){
            steps{
                echo "Testing realase ${REALASE}"
                writeFile file: 'test-results.txt', text: 'passed'
            }
        }
    }
    post{
        success{
            archiveArtifacts 'test-results.txt'
        }
    }
}