pipeline {
    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    environment {
        VERSION="0.1.2"
        VERSION_RC="rc.2"
    }
    stages {
        stage('Audit tools'){
            steps {
                echo "Sprawdzam zależności..."
                sh '''
                    git version
                    docker version
                '''
            }
        }
        stage('Build'){
            environment {
                VERSION_SUFFIX = "${sh(script:'if [ "${RC}" == "false" ] ; then echo -n "${VERSION_RC}+ci.${BUILD_NUMBER}"; else echo -n "${VERSION_RC}"; fi', returnStdout: true)}"
            }
            steps{
                echo "Building version $VERSION with suffix: ${VERSION_SUFFIX}"
            }
        }
        stage('Deploy'){
            when{
                expression { return params.RC}
            }
            steps {
                echo "Deploing $VERSION and RC-V $VERSION_RC"
            }
        }
    }
}

